import {GBBArchivo, GBBData, GBBFinalData, GBBNotaData} from './GBB.interface';

export function createEmptyGBBData(): GBBData {
    return {
        id_fase: 0,
        created_at: '',
        empresa: '1',
        empresa_externa: '',
        empresa_externa_razon: '',
        empresa_razon: '',
        factura_serie: '',
        factura_folio: '',
        mkt_coupon: 0,
        mkt_total: 0,
        nota: 'N/A',
        notas: [],
        almacen: '',
        no_venta: '',
        refacturado: 0,
        observacion: '',
        referencia: '',
        marketplace: '',
        periodo: '',
        serie: '',
        area: '',
        paqueteria: '',
        paqueteria_url: '',
        productos: [],
        series: [],
        seguimiento_anterior: [],
        direccion: {},
        criterio: '',
        campo: '',
        cliente: '',
        rfc: '',
        correo: '',
        telefono: '',
        telefono_alt: '',
        archivos: [],
        guias: [],
        pagos: [],
        pago: [],
        timbrado: 0,
        cancelada: 0,
        eliminada: 0,
        moneda: '',
        tipo_cambio: 0,
        modelo_proveedor_id: 0,
        modelo_proveedor: '',
        modelo_proveedor_venta: '',
        fecha_surtido: '',
        empaquetador: '',
        metodo_pago: '',
        forma_pago: '',
        api: {
            id: 0,
            publico: 1,
            marketplace: 'MERCADOLIBRE',
            id_marketplace_area: 0,
        },
        extra_info: {},
        nota_pendiente: false,
        usuario_agro: 0,
        refacturacion_pendiente: 0,
        documento_extra: ''
    };
}

export function createEmptyGBBFinalData(): GBBFinalData {
    return{
        documento: '',
        seguimiento: '',
        archivos: [],
        necesita_token: false,
        token: '',
    };
}

export function createEmptyGBBNotaData(): GBBNotaData {
    return {
        almacen: '',
        cancelado: null,
        cancelado_estado: 0,
        cancelado_por: null,
        cliente: '',
        detalle: [],
        documento: 0,
        eliminado_por: 0,
        eliminado: 0,
        fecha: '',
        folio: '',
        idalmacen: 0,
        moneda: '',
        monedaid: '',
        resta: 0,
        subtotal: 0,
        impuesto: 0,
        rfc: '',
        serie: '',
        timbrado_estado: '',
        tipo_cambio: 0,
        total: 0,
        uuid: '',
        documentos_pagos: [],
        empresa: '1',
        estado: '',
        titulo: '',
        marketplace: '',
        periodo: '',
        empresa_name: '',
        almacen_name: '',
        metodo_pago: '',
        uso_cod: '',
        uso_desc: '',
        formap: '',
        formapago: '',
    };
}

export function  createEmptyGBBArchivo(): GBBArchivo {
    return {
        guia: '',
        tipo: '',
        impresora: '',
        nombre: '',
        contenido: '',
    };
}

